### ISSUE TITLE
Extension looks for the models in the incorrect folder

### ISSUE THREAD

**Issue by ikcii** [jtydhr88/ComfyUI-Unique3D#4] opened 2024-06-24 02:23 UTC
Sometimes the extension looks for the correct folder:
`ComfyUI/custom_nodes/ComfyUI-Unique3D/ckpt`
But sometimes it looks for:
`ComfyUI/custom_nodes/ComfyUI-Unique3D/custom_nodes/ComfyUI-Unique3D/ckpt`
Which doesn't / shouldn't exist.

I fixed it for now by creating a symlink

**Comment by jtydhr88** [comment] 2024-06-24 02:30
Could you share the full error log while it happens?

**Comment by chflame163** [comment] 2024-06-24 12:51
Same issue.

```
got prompt
2024-06-24 20:44:58.8674067 [E:onnxruntime:Default, provider_bridge_ort.cc:1730 onnxruntime::TryGetProviderInfo_TensorRT] C:\a\_work\1\s\onnxruntime\core\session\provider_bridge_ort.cc:1426 onnxruntime::ProviderLibrary::Get [ONNXRuntimeError] : 1 : FAIL : LoadLibrary failed with error 126 "" when trying to load "D:\k-ComfyUI\python_embeded\Lib\site-packages\onnxruntime\capi\onnxruntime_providers_tensorrt.dll"

*************** EP Error ***************
EP Error C:\a\_work\1\s\onnxruntime\python\onnxruntime_pybind_state.cc:456 onnxruntime::python::RegisterTensorRTPluginsAsCustomOps Please install TensorRT libraries as mentioned in the GPU requirements page, make sure they're in the PATH or LD_LIBRARY_PATH, and that your GPU is supported.
 when using [('TensorrtExecutionProvider', {'device_id': 0, 'trt_max_workspace_size': 8589934592, 'trt_fp16_enable': True, 'trt_engine_cache_enable': True}), ('CUDAExecutionProvider', {'device_id': 0, 'arena_extend_strategy': 'kSameAsRequested', 'gpu_mem_limit': 8589934592, 'cudnn_conv_algo_search': 'HEURISTIC'})]
Falling back to ['CUDAExecutionProvider', 'CPUExecutionProvider'] and retrying.
****************************************
PyTorch version 2.2.1+cu121 available.
TensorFlow version 2.15.0 available.
Warning! extra parameter in cli is not verified, may cause erros.
!!! Exception during processing!!! We couldn't connect to 'https://huggingface.co' to load this model, couldn't find it in the cached files and it looks like D:/k-ComfyUI/ComfyUI/custom_nodes/ComfyUI-Unique3D/custom_nodes/ComfyUI-Unique3D/ckpt/img2mvimg is not the path to a directory containing a config.json file.
Checkout your internet connection or see how to run the library in offline mode at 'https://huggingface.co/docs/diffusers/installation#offline-mode'.
Traceback (most recent call last):
  File "D:\k-ComfyUI\python_embeded\Lib\site-packages\diffusers\configuration_utils.py", line 380, in load_config
    config_file = hf_hub_download(
                  ^^^^^^^^^^^^^^^^
  File "D:\k-ComfyUI\python_embeded\Lib\site-packages\huggingface_hub\utils\_validators.py", line 110, in _inner_fn
    validate_repo_id(arg_value)
  File "D:\k-ComfyUI\python_embeded\Lib\site-packages\huggingface_hub\utils\_validators.py", line 158, in validate_repo_id
    raise HFValidationError(
huggingface_hub.utils._validators.HFValidationError: Repo id must be in the form 'repo_name' or 'namespace/repo_name': 'D:/k-ComfyUI/ComfyUI/custom_nodes/ComfyUI-Unique3D/custom_nodes/ComfyUI-Unique3D/ckpt/img2mvimg'. Use `repo_type` argument if needed.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\k-ComfyUI\ComfyUI\execution.py", line 151, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\k-ComfyUI\ComfyUI\execution.py", line 81, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\k-ComfyUI\ComfyUI\execution.py", line 74, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\k-ComfyUI\ComfyUI\custom_nodes\ComfyUI-Unique3D\run.py", line 101, in run
    from .app.custom_models.mvimg_prediction import run_mvprediction
  File "D:\k-ComfyUI\ComfyUI\custom_nodes\ComfyUI-Unique3D\app\custom_models\mvimg_prediction.py", line 24, in <module>
    trainer, pipeline = load_pipeline(training_config, checkpoint_path)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\k-ComfyUI\ComfyUI\custom_nodes\ComfyUI-Unique3D\app\custom_models\utils.py", line 56, in load_pipeline
    trainers, configurable_unet = init_trainers(training_config, weight_dtype, extras)
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\k-ComfyUI\ComfyUI\custom_nodes\ComfyUI-Unique3D\app\custom_models\utils.py", line 21, in init_trainers
    configurable_unet = ConfigurableUNet2DConditionModel(init_config, weight_dtype)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\k-ComfyUI\ComfyUI/custom_nodes/ComfyUI-Unique3D\custum_3d_diffusion\custum_modules\unifield_processor.py", line 142, in __init__
    self.set_config(init_config)
  File "D:\k-ComfyUI\ComfyUI/custom_nodes/ComfyUI-Unique3D\custum_3d_diffusion\custum_modules\unifield_processor.py", line 205, in set_config
    self.unet: UnifieldWrappedUNet = unet_type.from_pretrained(
                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\k-ComfyUI\python_embeded\Lib\site-packages\huggingface_hub\utils\_validators.py", line 118, in _inner_fn
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "D:\k-ComfyUI\python_embeded\Lib\site-packages\diffusers\models\modeling_utils.py", line 567, in from_pretrained
    config, unused_kwargs, commit_hash = cls.load_config(
                                         ^^^^^^^^^^^^^^^^
  File "D:\k-ComfyUI\python_embeded\Lib\site-packages\huggingface_hub\utils\_validators.py", line 118, in _inner_fn
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "D:\k-ComfyUI\python_embeded\Lib\site-packages\diffusers\configuration_utils.py", line 415, in load_config
    raise EnvironmentError(
OSError: We couldn't connect to 'https://huggingface.co' to load this model, couldn't find it in the cached files and it looks like D:/k-ComfyUI/ComfyUI/custom_nodes/ComfyUI-Unique3D/custom_nodes/ComfyUI-Unique3D/ckpt/img2mvimg is not the path to a directory containing a config.json file.
Checkout your internet connection or see how to run the library in offline mode at 'https://huggingface.co/docs/diffusers/installation#offline-mode'.

Prompt executed in 300.16 seconds
```

**Comment by jtydhr88** [comment] 2024-06-25 01:18
thanks for the reporting, this issue caused by a wrong logic (fixed now), and for your end, you can go to:
![image](https://github.com/jtydhr88/ComfyUI-Unique3D/assets/860985/77c5bf41-8e16-4177-a9fd-534248d5a220)
this path might be wrong and if it is wrong please correct it to the right path.

**Comment by jtydhr88** [comment] 2024-06-28 14:10
since no more information comes, I would like to close this issue for now, please feel free to reopen it if you guys still need it.

**Closed as completed by jtydhr88** 2024-06-28 14:10 UTC
